name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f6cc1eb13d98b0ebadd85f9
